"""create service delivery tables

Revision ID: 3b34dd03d5b4
Revises: a62ce2a63316
Create Date: 2026-01-21 06:12:58.716660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b34dd03d5b4'
down_revision: Union[str, None] = 'a62ce2a63316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # =========================================================
    # TABEL WEBSITE INSTANCES (Project)
    # =========================================================
    op.create_table('website_instances',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('subdomain', sa.String(), nullable=True),
        sa.Column('custom_domain', sa.String(), nullable=True),
        sa.Column('server_ip', sa.String(), nullable=True),
        sa.Column('stage', sa.String(), nullable=True),
        sa.Column('repo_url', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        # Kita pasang Foreign Key karena tabel 'orders' dan 'users' SUDAH ADA (Dummy) di DB
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # Indexing agar pencarian cepat
    op.create_index(op.f('ix_website_instances_id'), 'website_instances', ['id'], unique=False)
    op.create_index(op.f('ix_website_instances_order_id'), 'website_instances', ['order_id'], unique=False)
    op.create_index(op.f('ix_website_instances_subdomain'), 'website_instances', ['subdomain'], unique=True)
    op.create_index(op.f('ix_website_instances_user_id'), 'website_instances', ['user_id'], unique=False)

    # =========================================================
    # TABEL PROJECT MILESTONES (Checklist)
    # =========================================================
    op.create_table('project_milestones',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('website_instance_id', sa.Integer(), nullable=True),
        sa.Column('task_name', sa.String(), nullable=False),
        sa.Column('is_completed', sa.Boolean(), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['website_instance_id'], ['website_instances.id'], )
    )
    op.create_index(op.f('ix_project_milestones_id'), 'project_milestones', ['id'], unique=False)

    # =========================================================
    # TABEL TICKETS (Support)
    # =========================================================
    op.create_table('tickets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('subject', sa.String(), nullable=False),
        sa.Column('priority', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)

    # =========================================================
    # TABEL TICKET MESSAGES (Chat Support)
    # =========================================================
    op.create_table('ticket_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ticket_id', sa.Integer(), nullable=True),
        sa.Column('sender_id', sa.Integer(), nullable=True),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], )
    )
    op.create_index(op.f('ix_ticket_messages_id'), 'ticket_messages', ['id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Kita hanya menghapus tabel milik Dev 3.
    # Jangan menyentuh tabel users/orders dummy.
    
    op.drop_index(op.f('ix_ticket_messages_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    
    op.drop_index(op.f('ix_project_milestones_id'), table_name='project_milestones')
    op.drop_table('project_milestones')
    
    op.drop_index(op.f('ix_website_instances_user_id'), table_name='website_instances')
    op.drop_index(op.f('ix_website_instances_subdomain'), table_name='website_instances')
    op.drop_index(op.f('ix_website_instances_order_id'), table_name='website_instances')
    op.drop_index(op.f('ix_website_instances_id'), table_name='website_instances')
    op.drop_table('website_instances')
    # ### end Alembic commands ###